version: '2'

services:
  wagtail:
    build:
      context: .
      dockerfile: ./tools/docker/Dockerfile
    command: /start-dev.sh
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./logs:/logs
