Vagrant.configure(2) do |config|

    #-------------------------------------------------------------
    # development
    #-------------------------------------------------------------
    config.vm.define "dev" do |dev|
        # vagrant box
        dev.vm.box = "ubuntu/xenial64"

        # ports to access the virtual machine
        dev.vm.network "forwarded_port", guest: 8000, host: 8111,
            auto_correct: true

        # private network
        dev.vm.network "private_network", type: "dhcp"

        # shared folder setup
        dev.vm.synced_folder ".", "/home/vagrant/{{cookiecutter.repo_name}}"

        # SSH agent forwarding
        dev.ssh.forward_agent = true

        # provisioning script
        dev.vm.provision "shell", path: "tools/vagrant/provision-dev.sh",
            privileged: false
    end

    #-------------------------------------------------------------
    # qa
    #-------------------------------------------------------------
    config.vm.define "qa", autostart: false do |qa|
       # vagrant box
       dev.vm.box = "ubuntu/xenial64"

       # ports to access the virtual machine
       qa.vm.network "forwarded_port", guest: 80, host: 8112,
           auto_correct: true

       # private network
       qa.vm.network "private_network", type: "dhcp"

       # shared folder setup
       qa.vm.synced_folder ".", "/home/vagrant/{{ cookiecutter.repo_name }}"

       # SSH agent forwarding
       qa.ssh.forward_agent = true

       # provisioning script
       qa.vm.provision "shell", path: "tools/vagrant/provision-qa.sh",
           privileged: false
    end

end
